/**
 * BiasBreaker Export Utilities
 * TypeScript utilities for exporting analysis reports to PDF
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { Analysis, BiasType } from '@/types';

// ============================================================================
// Types
// ============================================================================

interface BiasTypeInfo {
  label: string;
  color: [number, number, number];
}

// ============================================================================
// Constants
// ============================================================================

const BIAS_TYPE_LABELS: Record<BiasType, BiasTypeInfo> = {
  gender_bias: { label: 'Gender Bias', color: [236, 72, 153] }, // pink-500
  department_discrimination: { label: 'Department Discrimination', color: [59, 130, 246] }, // blue-500
  socioeconomic_bias: { label: 'Socioeconomic Bias', color: [245, 158, 11] }, // orange-500
  academic_elitism: { label: 'Academic Elitism', color: [124, 58, 237] }, // purple-600
  community_patterns: { label: 'Community Patterns', color: [16, 185, 129] }, // green-500
};

const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  low: [16, 185, 129], // green
  medium: [245, 158, 11], // orange
  high: [239, 68, 68], // red
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Adds footer to all pages
 */
function addFooterToAllPages(doc: jsPDF): void {
  const totalPages = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by BiasBreaker | ${format(new Date(), 'MMM d, yyyy')} | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }
}

/**
 * Capitalizes first letter of each word
 */
function capitalizeWords(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// ============================================================================
// Export Functions
// ============================================================================

/**
 * Exports a single analysis as a formatted PDF report
 * @param analysis - The analysis to export
 */
export function exportAnalysisPDF(analysis: Analysis): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // ========================
  // Header Section
  // ========================
  
  // Purple gradient header
  doc.setFillColor(79, 70, 229); // #4F46E5
  doc.rect(0, 0, pageWidth, 45, 'F');

  // Logo icon placeholder
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text('🎯', 14, 25);

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('BiasBreaker', 34, 20);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Campus Placement Bias Detection Report', 34, 28);

  // Analysis title on header
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(analysis.title || 'Untitled Analysis', 34, 38);

  // ========================
  // Analysis Summary Section
  // ========================
  
  doc.setTextColor(0, 0, 0);
  let yPos = 55;

  // Section title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Summary', 14, yPos);
  yPos += 10;

  // Summary details
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const summaryData = [
    ['Date Analyzed:', format(analysis.timestamp, "MMMM d, yyyy 'at' h:mm a")],
    ['Bias Score:', `${analysis.biasScore}%`],
    ['Severity:', capitalizeWords(analysis.severity)],
    ['Patterns Found:', `${analysis.detectedPatterns.length}`],
    ['Bias Types:', analysis.biasTypes.length > 0 ? analysis.biasTypes.map(t => BIAS_TYPE_LABELS[t].label).join(', ') : 'None detected'],
  ];

  summaryData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 55, yPos);
    yPos += 7;
  });

  // ========================
  // Bias Score Visualization
  // ========================
  
  yPos += 5;
  
  // Score indicator
  doc.setFont('helvetica', 'bold');
  doc.text('Bias Score Indicator:', 14, yPos);
  yPos += 5;
  
  // Progress bar background
  const barWidth = 100;
  const barHeight = 10;
  doc.setFillColor(229, 231, 235); // gray-200
  doc.roundedRect(14, yPos, barWidth, barHeight, 2, 2, 'F');
  
  // Progress bar fill
  const [r, g, b] = SEVERITY_COLORS[analysis.severity];
  doc.setFillColor(r, g, b);
  doc.roundedRect(14, yPos, (analysis.biasScore / 100) * barWidth, barHeight, 2, 2, 'F');
  
  // Score text
  doc.setTextColor(r, g, b);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(`${analysis.biasScore}%`, 120, yPos + 8);
  
  doc.setTextColor(0, 0, 0);
  yPos += 20;

  // ========================
  // Original Text Section
  // ========================
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Analyzed Content', 14, yPos);
  yPos += 8;

  // Content box
  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(249, 250, 251); // gray-50
  
  const contentLines = doc.splitTextToSize(analysis.text, pageWidth - 35);
  const maxLines = 12;
  const displayLines = contentLines.slice(0, maxLines);
  const boxHeight = Math.min(displayLines.length * 5 + 10, 70);
  
  doc.roundedRect(14, yPos, pageWidth - 28, boxHeight, 2, 2, 'FD');
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99); // gray-600
  
  let lineY = yPos + 7;
  displayLines.forEach((line: string) => {
    doc.text(line, 18, lineY);
    lineY += 5;
  });
  
  if (contentLines.length > maxLines) {
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(156, 163, 175); // gray-400
    doc.text('... (content truncated for brevity)', 18, lineY);
  }
  
  doc.setTextColor(0, 0, 0);
  yPos += boxHeight + 15;

  // ========================
  // Detected Patterns Section
  // ========================
  
  if (analysis.detectedPatterns.length > 0) {
    // Check if we need a new page
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Detected Bias Patterns', 14, yPos);
    yPos += 5;

    const patternsTableData = analysis.detectedPatterns.map((pattern, index) => [
      (index + 1).toString(),
      BIAS_TYPE_LABELS[pattern.type]?.label || capitalizeWords(pattern.type),
      capitalizeWords(pattern.severity),
      pattern.text.length > 60 ? pattern.text.substring(0, 60) + '...' : pattern.text,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['#', 'Bias Type', 'Severity', 'Text Snippet']],
      body: patternsTableData,
      theme: 'striped',
      headStyles: {
        fillColor: [79, 70, 229], // purple
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 12 },
        1: { cellWidth: 40 },
        2: { cellWidth: 25 },
        3: { cellWidth: 'auto' },
      },
      margin: { left: 14, right: 14 },
      didParseCell: (data) => {
        // Color-code severity column
        if (data.column.index === 2 && data.section === 'body') {
          const severity = data.cell.raw?.toString().toLowerCase() || '';
          const color = SEVERITY_COLORS[severity];
          if (color) {
            data.cell.styles.textColor = color;
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
    });

    // Get the final Y position after the table
    yPos = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || yPos + 50;
    yPos += 15;
  }

  // ========================
  // Suggestions Section
  // ========================
  
  if (analysis.suggestions.length > 0) {
    // Check if we need a new page
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Improvement Suggestions', 14, yPos);
    yPos += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    analysis.suggestions.forEach((suggestion, index) => {
      // Check if we need a new page
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }

      // Number badge
      doc.setFillColor(79, 70, 229);
      doc.circle(18, yPos - 1, 4, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text((index + 1).toString(), 16.5, yPos + 1);

      // Suggestion text
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      const suggestionLines = doc.splitTextToSize(suggestion, pageWidth - 45);
      suggestionLines.forEach((line: string) => {
        doc.text(line, 28, yPos);
        yPos += 5;
      });
      yPos += 5;
    });
  }

  // ========================
  // Add Footers
  // ========================
  addFooterToAllPages(doc);

  // ========================
  // Save PDF
  // ========================
  const fileName = `${(analysis.title || 'analysis').replace(/[^a-z0-9]/gi, '-').toLowerCase()}-report.pdf`;
  doc.save(fileName);
}

/**
 * Exports multiple analyses as a summary PDF report
 * @param analyses - Array of analyses to export
 * @param title - Optional title for the report
 */
export function exportAnalysesSummaryPDF(analyses: Analysis[], title = 'My Analyses Summary'): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // ========================
  // Cover Page
  // ========================
  
  doc.setFillColor(79, 70, 229); // purple
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.height, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text('🎯 BiasBreaker', pageWidth / 2, 80, { align: 'center' });

  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.text(title, pageWidth / 2, 100, { align: 'center' });

  doc.setFontSize(12);
  doc.text(`Generated on ${format(new Date(), 'MMMM d, yyyy')}`, pageWidth / 2, 120, { align: 'center' });

  // Statistics
  const totalAnalyses = analyses.length;
  const avgScore = totalAnalyses > 0
    ? Math.round(analyses.reduce((sum, a) => sum + a.biasScore, 0) / totalAnalyses)
    : 0;
  const highSeverity = analyses.filter((a) => a.severity === 'high').length;
  const mediumSeverity = analyses.filter((a) => a.severity === 'medium').length;
  const lowSeverity = analyses.filter((a) => a.severity === 'low').length;

  doc.setFontSize(14);
  doc.text(`Total Analyses: ${totalAnalyses}`, pageWidth / 2, 150, { align: 'center' });
  doc.text(`Average Bias Score: ${avgScore}%`, pageWidth / 2, 165, { align: 'center' });
  doc.text(`High: ${highSeverity} | Medium: ${mediumSeverity} | Low: ${lowSeverity}`, pageWidth / 2, 180, { align: 'center' });

  // ========================
  // Summary Table Page
  // ========================
  
  doc.addPage();
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Summary', 14, 20);

  const tableData = analyses.map((analysis, index) => [
    (index + 1).toString(),
    (analysis.title || 'Untitled').substring(0, 30),
    format(analysis.timestamp, 'MMM d, yyyy'),
    `${analysis.biasScore}%`,
    capitalizeWords(analysis.severity),
    analysis.detectedPatterns.length.toString(),
  ]);

  autoTable(doc, {
    startY: 28,
    head: [['#', 'Title', 'Date', 'Score', 'Severity', 'Patterns']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 60 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 },
    },
    margin: { left: 14, right: 14 },
    didParseCell: (data) => {
      // Color-code severity column
      if (data.column.index === 4 && data.section === 'body') {
        const severity = data.cell.raw?.toString().toLowerCase() || '';
        const color = SEVERITY_COLORS[severity];
        if (color) {
          data.cell.styles.textColor = color;
          data.cell.styles.fontStyle = 'bold';
        }
      }
      // Color-code score column
      if (data.column.index === 3 && data.section === 'body') {
        const score = parseInt(data.cell.raw?.toString() || '0', 10);
        if (score < 30) {
          data.cell.styles.textColor = SEVERITY_COLORS.low;
        } else if (score <= 70) {
          data.cell.styles.textColor = SEVERITY_COLORS.medium;
        } else {
          data.cell.styles.textColor = SEVERITY_COLORS.high;
        }
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // ========================
  // Add Footers
  // ========================
  addFooterToAllPages(doc);

  // ========================
  // Save PDF
  // ========================
  doc.save(`biasbreaker-analyses-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}
