import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';


// Export individual analysis as PDF
export const exportAnalysisPDF = (analysis) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Header
  doc.setFillColor(59, 130, 246); // Blue
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  // Logo/Icon
  doc.setFontSize(24);
  doc.text('🎯', 14, 20);
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('BiasBreaker Analysis Report', 30, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Campus Placement Bias Detection', 30, 26);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Document Info
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis Details', 14, 50);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  const details = [
    ['Email Title:', analysis.fileName || 'Untitled Email'],
    ['Date:', new Date(analysis.timestamp).toLocaleString('en-IN')],
    ['Status:', analysis.analysis?.biasDetected ? '⚠️ Bias Detected' : '✅ No Bias Found'],
    ['Confidence:', `${analysis.analysis?.confidence || 0}%`],
    ['Total Patterns:', `${analysis.analysis?.patterns?.length || 0}`]
  ];
  
  let yPos = 58;
  details.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 60, yPos);
    yPos += 7;
  });
  
  // Original Email Content
  yPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Original Email Content', 14, yPos);
  
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  
  const emailLines = doc.splitTextToSize(analysis.emailText, pageWidth - 28);
  const maxEmailLines = 15;
  emailLines.slice(0, maxEmailLines).forEach(line => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 14, yPos);
    yPos += 5;
  });
  
  if (emailLines.length > maxEmailLines) {
    doc.setFont('helvetica', 'italic');
    doc.text('... (content truncated)', 14, yPos);
  }
  
  // Bias Patterns Table
  if (analysis.analysis?.patterns && analysis.analysis.patterns.length > 0) {
    doc.addPage();
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Detected Bias Patterns', 14, 20);
    
    const tableData = analysis.analysis.patterns.map((pattern, index) => [
      index + 1,
      pattern.type?.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) || 'Unknown',
      pattern.severity?.toUpperCase() || '-',
      pattern.evidence?.substring(0, 50) + '...' || '-',
      pattern.reasoning?.substring(0, 80) + '...' || '-'
    ]);
    
    autoTable(doc, {
      startY: 28,
      head: [['#', 'Type', 'Severity', 'Evidence', 'AI Reasoning']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 35 },
        2: { cellWidth: 20 },
        3: { cellWidth: 50 },
        4: { cellWidth: 65 }
      },
      margin: { top: 28, left: 14, right: 14 }
    });
  }
  
  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by BiasBreaker | ${new Date().toLocaleDateString('en-IN')} | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }
  
  // Save PDF
  const fileName = `${analysis.fileName || 'analysis'}-report.pdf`;
  doc.save(fileName);
  
  // Show success toast
  if (typeof window !== 'undefined') {
    toast.success(`📄 PDF exported: ${fileName}`);
  }
};

// Export all reports as comprehensive PDF
export const exportAllReportsPDF = (uploads, stats) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Cover Page
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.height, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('🎯 BiasBreaker', pageWidth / 2, 80, { align: 'center' });
  
  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.text('Comprehensive Analytics Report', pageWidth / 2, 100, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(`Generated on ${new Date().toLocaleString('en-IN')}`, pageWidth / 2, 120, { align: 'center' });
  
  doc.text(`Total Emails Analyzed: ${stats.total}`, pageWidth / 2, 140, { align: 'center' });
  doc.text(`Bias Detected: ${stats.withBias}`, pageWidth / 2, 150, { align: 'center' });
  doc.text(`Average Confidence: ${stats.avgConfidence}%`, pageWidth / 2, 160, { align: 'center' });
  
  // Summary Page
  doc.addPage();
  doc.setTextColor(0, 0, 0);
  
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, 20);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const summaryY = 35;
  autoTable(doc, {
    startY: summaryY,
    head: [['Metric', 'Value']],
    body: [
      ['Total Emails Analyzed', stats.total.toString()],
      ['Emails with Bias', stats.withBias.toString()],
      ['Clean Emails', stats.withoutBias.toString()],
      ['Average Confidence Score', `${stats.avgConfidence}%`],
      ['Bias Detection Rate', `${stats.total > 0 ? Math.round((stats.withBias / stats.total) * 100) : 0}%`]
    ],
    theme: 'striped',
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: 255,
      fontStyle: 'bold'
    }
  });
  
  // Analysis List
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Analysis History', 14, 20);
  
  const tableData = uploads.slice(0, 20).map((upload, index) => [
    index + 1,
    upload.fileName || 'Untitled',
    new Date(upload.timestamp).toLocaleDateString('en-IN'),
    upload.analysis?.biasDetected ? 'Yes' : 'No',
    `${upload.analysis?.confidence || 0}%`,
    upload.analysis?.patterns?.length || 0
  ]);
  
  autoTable(doc, {
    startY: 28,
    head: [['#', 'Title', 'Date', 'Bias', 'Confidence', 'Patterns']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: 255,
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 70 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 }
    }
  });
  
  // Footer on all pages
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `BiasBreaker Analytics Report | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }
  
  const fileName = `biasbreaker-full-report-${Date.now()}.pdf`;
  doc.save(fileName);
  
  if (typeof window !== 'undefined') {
    toast.success('📄 Full report PDF exported!');
  }
};

// Export detailed CSV
export const exportDetailedCSV = (uploads) => {
  const csvRows = [];
  
  // Header
  csvRows.push([
    'Email Title',
    'Upload Date',
    'Upload Time',
    'Bias Detected',
    'Confidence (%)',
    'Total Patterns',
    'High Severity',
    'Medium Severity',
    'Low Severity',
    'Bias Types',
    'Evidence Summary'
  ].join(','));
  
  // Data rows
  uploads.forEach(upload => {
    const patterns = upload.analysis?.patterns || [];
    const biasTypes = patterns.map(p => p.type?.replace(/_/g, ' ')).join('; ');
    const evidence = patterns.map(p => p.evidence?.substring(0, 30)).join('; ');
    
    const highCount = patterns.filter(p => p.severity === 'high').length;
    const mediumCount = patterns.filter(p => p.severity === 'medium').length;
    const lowCount = patterns.filter(p => p.severity === 'low').length;
    
    const date = new Date(upload.timestamp);
    
    csvRows.push([
      `"${upload.fileName || 'Untitled'}"`,
      date.toLocaleDateString('en-IN'),
      date.toLocaleTimeString('en-IN'),
      upload.analysis?.biasDetected ? 'Yes' : 'No',
      upload.analysis?.confidence || 0,
      patterns.length,
      highCount,
      mediumCount,
      lowCount,
      `"${biasTypes}"`,
      `"${evidence}"`
    ].join(','));
  });
  
  const csv = csvRows.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const fileName = `biasbreaker-detailed-export-${Date.now()}.csv`;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);

  if (typeof window !== 'undefined') {
    toast.success(`📊 CSV exported: ${fileName}`);
  }
};

// Generate shareable report link (returns data object)
export const generateShareableReport = (analysis) => {
  return {
    title: analysis.fileName || 'BiasBreaker Analysis',
    summary: `${analysis.analysis?.biasDetected ? 'Bias Detected' : 'No Bias Found'} with ${analysis.analysis?.confidence || 0}% confidence`,
    patterns: analysis.analysis?.patterns?.length || 0,
    date: new Date(analysis.timestamp).toLocaleDateString('en-IN'),
    url: typeof window !== 'undefined' ? window.location.href : ''
  };
};
